### ISSUE TITLE
Bug: Cannot assign two dependencies to one task simultaneously

### ISSUE THREAD

**Issue by rccalma** [ksalzke/dependency-omnifocus-plugin#30]
Hi,

I am having an issue where I  cannot add multiple dependencies to one task. For example, I have two tasks (A and B) both of which get assigned the prerequisite marker ("Marker"). I click on the task I want to be dependent on the other two. I run "Add Prerequisite," and the respective tasks are properly tagged (A & B are now tagged with PreReq, the task is now tagged as Task). When I click "Remove PreRequisite(s), only task B is listed.

The two tasks are properly linked to the third task if I set their dependencies individually.

**Comment by ksalzke** [comment]
Can confirm that I can reproduce this.

I will take a look, thanks.
